package co.unicauca.hyunseda.client.presentation;

import co.unicauca.hyunseda.client.access.model.Product;
import co.unicauca.hyunseda.client.domain.services.ProductService;
import co.unicauca.hyunseda.client.domain.services.ShoppingCartService;
import co.unicauca.hyunseda.client.infra.Observer;
import co.unicauca.hyunseda.client.infra.Utilities;
import com.fasterxml.jackson.core.type.TypeReference;
import java.awt.Image;
import java.io.IOException;
import java.net.http.HttpResponse;
import javax.swing.JOptionPane;

import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Libardo Pantoja, Julio A. Hurtado
 */
public class GUIClientMenu extends javax.swing.JFrame implements Observer{
    private GUIClientCart GUICart;
    private GUIClientAddProductCartConfirmation GUICartConf;
    
    /**
     * Creates new form GUIProductsFind
     */
    public GUIClientMenu() {
        initComponents();
        initializeTable();
        
        GUICart = new GUIClientCart();
        GUICartConf = new GUIClientAddProductCartConfirmation();
        
        setLocationRelativeTo(null); //centrar al ventana
        this.flagImage = 0;
        
        ShoppingCartService.getShoppingCartService().addObserver(GUICart);
        GUICart.setSize(300, 200);
        GUICart.setVisible(true);
        
    }
    
    private void initializeTable() {
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Name", "Description", "Price", "ID"
                }
        ));
        tblProducts.getColumnModel().getColumn(3).setMinWidth(0);
        tblProducts.getColumnModel().getColumn(3).setMaxWidth(0);
        tblProducts.getColumnModel().getColumn(3).setWidth(0);
    }
    
    private void fillTable(List<Product> listProducts) {
        initializeTable();
        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();

        Object rowData[] = new Object[4];//No columnas
        for (int i = 0; i < listProducts.size(); i++) {
            rowData[0] = listProducts.get(i).getName();
            rowData[1] = listProducts.get(i).getDescription();
            rowData[2] = String.valueOf(listProducts.get(i).getPrice());
            rowData[3] = listProducts.get(i).getProductId();
            
            model.addRow(rowData);
        }
    }
    
    private void fillTable(Product product) {
        initializeTable();
        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();

        Object rowData[] = new Object[4];//No columnas
        rowData[0] = product.getName();
        rowData[1] = product.getDescription();
        rowData[2] = String.valueOf(product.getPrice());
        rowData[3] = product.getProductId();

        model.addRow(rowData);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectionSearchGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        lblImage = new javax.swing.JLabel();
        pnlNorth = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnSearchAll = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnCart = new javax.swing.JButton();

        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Búsqueda de productos");

        pnlCenter.setBackground(new java.awt.Color(102, 102, 102));
        pnlCenter.setLayout(new java.awt.BorderLayout());

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducts);

        pnlCenter.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setText("Image");
        lblImage.setPreferredSize(new java.awt.Dimension(200, 16));
        pnlCenter.add(lblImage, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        pnlNorth.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre Producto");
        pnlNorth.add(jLabel1);

        txtSearch.setName(""); // NOI18N
        txtSearch.setPreferredSize(new java.awt.Dimension(62, 32));
        pnlNorth.add(txtSearch);

        btnSearch.setBackground(new java.awt.Color(204, 204, 204));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/busqueda.png"))); // NOI18N
        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pnlNorth.add(btnSearch);

        btnSearchAll.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchAll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/busqueda.png"))); // NOI18N
        btnSearchAll.setText("Buscar Todos");
        btnSearchAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAllActionPerformed(evt);
            }
        });
        pnlNorth.add(btnSearchAll);

        getContentPane().add(pnlNorth, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        btnClose.setBackground(new java.awt.Color(204, 204, 204));
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/logout_1828427.png"))); // NOI18N
        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);

        btnCart.setBackground(new java.awt.Color(204, 204, 204));
        btnCart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/carrito-de-compras.png"))); // NOI18N
        btnCart.setText("Agregar Carrito");
        btnCart.setName(""); // NOI18N
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });
        jPanel1.add(btnCart);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        GUICart.dispose();
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSearchAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAllActionPerformed
        fillTable(ProductService.getProductService().getProducts());
    }//GEN-LAST:event_btnSearchAllActionPerformed
 
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            fillTable(ProductService.getProductService().getProductsByName(txtSearch.getText()));
        } catch (Exception e) {
            showMessage("Error", "Producto no encontrado. No se encontró ningún producto.");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    public static void showMessage(String title, String message) {
        JOptionPane.showMessageDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
            
        int selectedRow = tblProducts.getSelectedRow();
        if (selectedRow != -1) { // Verificar si se ha seleccionado una fila
            long id = Long.parseLong(String.valueOf(tblProducts.getValueAt(selectedRow, 3)));
            
            GUICartConf.setProductId(ProductService.getProductService().getProductById(id).getProductId());
            GUICartConf.setProductName(ProductService.getProductService().getProductById(id).getName());
            GUICartConf.setSize(300, 200);
            GUICartConf.setVisible(true);
        }
    }//GEN-LAST:event_btnCartActionPerformed

    private int flagImage;
    
    
    private void tblProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductsMouseClicked
        int selectedRow = tblProducts.getSelectedRow();
        
        //se se esta fuera del rango o si el clic ha sido dado sobre la misma columna por segunda vez
        if (selectedRow == -1 ||flagImage == selectedRow)
        {
            return;
        }
        
        //Se re escala la imagen y se pone en lblImage obteniendo el link de imagen del objeto
        long id = Long.parseLong(String.valueOf(tblProducts.getValueAt(selectedRow, 3)));
        ImageIcon imageIcon = Utilities.loadImageFromCloud(ProductService.getProductService().getProductById(id).getImageLink());

        //reescalar la imagen:
        int newWidth = 200;
        int newHeight = 200;
        Image resizedImage = imageIcon.getImage().getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);

        //Como el label esta con un objeto icon, hay que vover a cear un nuevo objeto para redimensionar bien la imagen
        ImageIcon resizedIcon = new ImageIcon(resizedImage);

        if (resizedIcon != null) {
            lblImage.setIcon(resizedIcon);
        }
        
        flagImage = selectedRow;
    }//GEN-LAST:event_tblProductsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCart;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlNorth;
    private javax.swing.ButtonGroup selectionSearchGroup;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Object o) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}