
package co.unicauca.hyunseda.client.presentation;

import co.unicauca.hyunseda.client.access.model.Item;
import co.unicauca.hyunseda.client.access.model.Order;
import co.unicauca.hyunseda.client.access.model.Product;
import co.unicauca.hyunseda.client.domain.services.ItemService;
import co.unicauca.hyunseda.client.domain.services.OrderService;
import co.unicauca.hyunseda.client.domain.services.ShoppingCartService;
import co.unicauca.hyunseda.client.infra.Observer;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oscar
 */
public class GUIClientCart extends javax.swing.JFrame implements Observer{
    private int amount;
    
    public GUIClientCart(){
        initComponents();
        ItemService.getItemService();
        // Obtener dimensiones de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para ubicar la ventana a la izquierda
        int x = 0; // Posición x en el borde izquierdo de la pantalla
        int y = (int) ((screenSize.getHeight() - getHeight()) / 2); // Centrado verticalmente

        // Establecer la ubicación de la ventana
        setLocation(x, y);
    }
    
    private void initializeTable() {
        tblProductsCart.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ProductId", "Amount"
                }
        ));
    }
    
    private void fillTableCart(List<Item> listItemShoppingCart) {
        initializeTable();
        DefaultTableModel model = (DefaultTableModel) tblProductsCart.getModel();

        Object rowData[] = new Object[2];//No columnas
        for (int i = 0; i < listItemShoppingCart.size(); i++) {
            rowData[0] = listItemShoppingCart.get(i).getProductId();
            rowData[1] = listItemShoppingCart.get(i).getAmount();

            model.addRow(rowData);
        }
    }
    
    private void fillTable(Product product) {
        initializeTable();
        DefaultTableModel model = (DefaultTableModel) tblProductsCart.getModel();

        Object rowData[] = new Object[3];//No columnas
        rowData[0] = product.getProductId();
        rowData[1] = product.getName();
        rowData[2] = product.getDescription();

        model.addRow(rowData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btmDeselect = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductsCart = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carrito");
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        btmDeselect.setBackground(new java.awt.Color(204, 204, 204));
        btmDeselect.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btmDeselect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ojos-cruzados.png"))); // NOI18N
        btmDeselect.setText("Deselect");
        btmDeselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmDeselectActionPerformed(evt);
            }
        });
        jPanel1.add(btmDeselect);

        btnCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cruz.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);

        btnPay.setBackground(new java.awt.Color(204, 204, 204));
        btnPay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/usd-circulo.png"))); // NOI18N
        btnPay.setText("Pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        jPanel1.add(btnPay);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("C A R T");
        jPanel2.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblProductsCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductsCart);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
//        for (Item i : ShoppingCartService.getShoppingCartService().getShoppingCart())
//        {
//            //ItemService.getItemService().postItem(i);
//            System.out.println(i.toString());
//        }
        OrderService.getOrderService().postOrder(new Order(0L, 1L, "12/21/20", "NotSend", ShoppingCartService.getShoppingCartService().getShoppingCart()));
        new GUIPay(ShoppingCartService.getShoppingCartService().getShoppingCart()).setVisible(true);
        
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        ShoppingCartService.getShoppingCartService().cleanShoppingCart();
        ShoppingCartService.getShoppingCartService().getShoppingCart();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btmDeselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmDeselectActionPerformed
        int indexAtTable  = tblProductsCart.getSelectedRow();
        
        if (indexAtTable == -1)
        {
            return;
        }
        
        Item item = new Item();
        item.setProductId(Long.valueOf(tblProductsCart.getValueAt(indexAtTable, 0).toString()));
        ShoppingCartService.getShoppingCartService().deleteShoppingCartElement(item);
    }//GEN-LAST:event_btmDeselectActionPerformed

    @Override
    public void update(Object o) {
        ShoppingCartService userServiceLocal = (ShoppingCartService) o;
        fillTableCart(userServiceLocal.getShoppingCart());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmDeselect;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPay;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductsCart;
    // End of variables declaration//GEN-END:variables
}
