/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.hyunseda.client.presentation;

import co.unicauca.hyunseda.client.access.model.Item;
import co.unicauca.hyunseda.client.access.model.Order;
import co.unicauca.hyunseda.client.access.model.Product;
import co.unicauca.hyunseda.client.domain.services.OrderService;
import co.unicauca.hyunseda.client.domain.services.ProductService;
import co.unicauca.hyunseda.client.infra.external.Messages;
import java.awt.Image;
import java.io.File;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Oscar
 */
public class GUIPay extends javax.swing.JFrame {

    List<Item> cart;
     
    /**
     * Creates new form GUIPago
     * @param cart
     */
    public GUIPay(List<Item> cart) {
        this.cart = cart;
        initComponents();
    }
    
    private static String getBaseFilePath() {
        try {
            String path = GUIPay.class.getProtectionDomain().getCodeSource().getLocation().getPath();
            path = URLDecoder.decode(path, "UTF-8"); //This should solve the problem with spaces and special characters.
            File pathFile = new File(path);
            if (pathFile.isFile()) {
                path = pathFile.getParent();
                if (!path.endsWith(File.separator)) {
                    path += File.separator;
                }
            }
            return path;
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(GUIPay.class.getName()).log(Level.SEVERE, "Error al eliminar espacios en la ruta del archivo", ex);
            return null;
        }
    }

    public GUIPay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbltit1 = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        txtAccountNumber = new javax.swing.JTextField();
        btnBuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PaySimulated");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        lbltit1.setBackground(new java.awt.Color(102, 102, 102));
        lbltit1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbltit1.setForeground(new java.awt.Color(255, 255, 255));
        lbltit1.setText("INFORMACIÓN DE CONTACTO");
        lbltit1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(lbltit1);

        lblNumber.setBackground(new java.awt.Color(102, 102, 102));
        lblNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblNumber.setText("Número:");
        jPanel1.add(lblNumber);

        txtAccountNumber.setBackground(new java.awt.Color(102, 102, 102));
        txtAccountNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountNumberActionPerformed(evt);
            }
        });
        jPanel1.add(txtAccountNumber);

        btnBuy.setBackground(new java.awt.Color(204, 204, 204));
        btnBuy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/usd-circulo.png"))); // NOI18N
        btnBuy.setText("contactame!");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuy);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        ImageIcon iconoConfirmacion = new ImageIcon("C:\\Users\\Oscar\\Desktop\\check.png");
        Image imagenOriginal = iconoConfirmacion.getImage();
        Image imagenRedimensionada = imagenOriginal.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        ImageIcon iconoRedimensionado = new ImageIcon(imagenRedimensionada);
        Long number = 0L;
        try
        {
            number = Long.valueOf(txtAccountNumber.getText());
            
            List<Order> orders = OrderService.getOrderService().getOrderByState("NotSend");
            orders.get(0).setClientId(number);
            OrderService.getOrderService().putOrder(orders.get(0), orders.get(0).getOrderId().toString());
            OrderService.getOrderService().executeOnHoldInOrder(orders.get(0).getOrderId().toString());
            JOptionPane.showMessageDialog(this, 
            "¡Enhorabuena! Nos contactaremos pronto contigo.", 
            "Confirmación", 
            JOptionPane.PLAIN_MESSAGE, iconoRedimensionado);

        }catch (Exception e)
        {
            System.out.println("co.unicauca.hyunseda.client.presentation.GUIPay.btnBuyActionPerformed()");
        }
        
        /*
        //Messages.sendPaymentConfirmationMessage();
        double charge = 0;
        Product p;
        
        for (Item i : cart)
        {
            p = ProductService.getProductService().getProductById(i.getProductId());
            charge = charge + p.getPrice()*i.getAmount();
        }*/
        
    }//GEN-LAST:event_btnBuyActionPerformed

    private void txtAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountNumberActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lbltit1;
    private javax.swing.JTextField txtAccountNumber;
    // End of variables declaration//GEN-END:variables
}
